"""Add status and soft delete

Revision ID: 2457485d5437
Revises: c323acfb740d
Create Date: 2026-02-21 22:41:33.504892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2457485d5437'
down_revision: Union[str, Sequence[str], None] = 'c323acfb740d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    status_enum = sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', 'BANNED', name='coursestatus')
    status_enum.create(op.get_bind())
    op.add_column('courses', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', 'BANNED', name='coursestatus'), nullable=False))
    op.add_column('courses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_deleted')
    op.drop_column('courses', 'status')

    sa.Enum(name='coursestatus').drop(op.get_bind())
    # ### end Alembic commands ###
