"""Add categories and relationships

Revision ID: c323acfb740d
Revises: 75f34be136e8
Create Date: 2026-02-21 21:13:52.626051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c323acfb740d'
down_revision: Union[str, Sequence[str], None] = '75f34be136e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_index(op.f('ix_courses_price'), table_name='courses')
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    op.drop_column('courses', 'category')
    op.drop_column('courses', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_index(op.f('ix_courses_price'), 'courses', ['price'], unique=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('courses', 'category_id')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
